# Generated by Django 5.2.3 on 2025-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='ticket_number',
            field=models.PositiveIntegerField(default=1, verbose_name='№ билета'),
            preserve_default=False,
        ),
    ]
