# Generated by Django 5.2.3 on 2025-06-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passengers', '0002_passenger_created_at_passenger_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название парома')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер судна')),
                ('ship_class', models.CharField(choices=[('0', 'Морские'), ('1', 'Рейдовые'), ('2', 'Внутреннего плавания'), ('3', 'Смешанного плавания')], max_length=1, verbose_name='Класс судна')),
                ('flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passengers.citizenship', verbose_name='Флаг регистрации')),
            ],
            options={
                'verbose_name': 'Паром',
                'verbose_name_plural': 'Паромы',
            },
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('rank', models.CharField(max_length=100, verbose_name='Должность')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('doc_number', models.CharField(max_length=50, verbose_name='Номер документа')),
                ('is_active', models.BooleanField(default=True, verbose_name='На смене')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.citizenship', verbose_name='Гражданство')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.doctype', verbose_name='Вид документа')),
                ('ferry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.ferry', verbose_name='Паром')),
            ],
            options={
                'verbose_name': 'Член экипажа',
                'verbose_name_plural': 'Экипаж',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рейса')),
                ('departure_port', models.CharField(max_length=100, verbose_name='Пункт отправления')),
                ('arrival_port', models.CharField(max_length=100, verbose_name='Пункт прибытия')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('arrival_time', models.TimeField(verbose_name='Время прибытия')),
                ('route_type', models.CharField(choices=[('0', 'Беспересадочный'), ('1', 'Транзитный')], max_length=1, verbose_name='Тип маршрута')),
                ('crew', models.ManyToManyField(related_name='schedules', to='route.crewmember', verbose_name='Экипаж')),
                ('ferry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.ferry', verbose_name='Паром')),
                ('passengers', models.ManyToManyField(related_name='schedules', to='passengers.passenger', verbose_name='Пассажиры')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='PassengerVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passengers.passenger', verbose_name='Пассажир')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.voyage', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Пассажир на пароме',
                'verbose_name_plural': 'Пассажиры на пароме',
            },
        ),
        migrations.CreateModel(
            name='CrewVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.crewmember', verbose_name='Экипаж')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.voyage', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Экипаж на пароме',
                'verbose_name_plural': 'Экипаж на пароме',
            },
        ),
    ]
