# Generated by Django 5.2.3 on 2025-06-30 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_voyage_crew_alter_voyage_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
