# Generated by Django 5.2.3 on 2025-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0003_crewmember_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="voyage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Статус рейса"),
        ),
    ]
