# Generated by Django 5.2.3 on 2025-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_citizenship_created_at_citizenship_created_by_and_more'),
        ('route', '0005_crewmember_created_by_crewvoyage_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='new_crew',
            field=models.ManyToManyField(blank=True, null=True, related_name='schedules', through='route.CrewVoyage', to='route.crewmember', verbose_name='Экипаж'),
        ),
        migrations.AddField(
            model_name='voyage',
            name='new_passenger',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_passenger', through='route.PassengerVoyage', to='passengers.passenger', verbose_name='Пассажиры'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='crew',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_crew', to='route.crewmember', verbose_name='Экипаж'),
        ),
    ]
