# Generated by Django 5.2.3 on 2025-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_voyage_new_crew_voyage_new_passenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='passengers',
        ),
    ]
