# Generated by Django 5.2.3 on 2025-07-08 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0009_alter_voyage_passenger"),
    ]

    operations = [
        migrations.RenameField(
            model_name="voyage",
            old_name="passenger",
            new_name="passengers",
        ),
    ]
