# Generated by Django 5.2.3 on 2025-06-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Citizenship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Гражданство"
                    ),
                ),
            ],
            options={
                "verbose_name": "Гражданство",
                "verbose_name_plural": "Гражданства",
            },
        ),
        migrations.CreateModel(
            name="DocType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название документа"),
                ),
                (
                    "pk_for_file",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Уникальный номер (для файла)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип документа",
                "verbose_name_plural": "Типы документов",
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.PositiveIntegerField(verbose_name="Номер билета"),
                ),
                ("surname", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Отчество"
                    ),
                ),
                ("birthday", models.DateField(verbose_name="Дата рождения")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужской"), ("F", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(max_length=50, verbose_name="Номер документа"),
                ),
                (
                    "citizenship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passengers.citizenship",
                        verbose_name="Гражданство",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passengers.doctype",
                        verbose_name="Вид документа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пассажир",
                "verbose_name_plural": "Пассажиры",
            },
        ),
    ]
