# Generated by Django 5.2.3 on 2025-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passengers", "0002_passenger_created_at_passenger_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctype",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Краткое название"
            ),
        ),
    ]
