# Generated by Django 5.2.3 on 2025-08-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0004_citizenship_created_at_citizenship_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add_passenger", "Добавил пассажира в базу"),
                            ("passenger_to_schedule", "Добавил пассажира на рейс"),
                            ("send_schedule", "Отправил рейс"),
                        ],
                        max_length=32,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создан пользователем",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
