# Generated by Django 5.2.3 on 2025-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passengers", "0005_userstats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userstats",
            options={"verbose_name": "Статистика", "verbose_name_plural": "Статистика"},
        ),
        migrations.AddField(
            model_name="userstats",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="userstats",
            name="action",
            field=models.CharField(
                choices=[
                    ("add_passenger", "Добавил пассажира в базу"),
                    ("passenger_to_schedule", "Добавил пассажиров на рейс"),
                    ("send_schedule", "Отправил рейс"),
                ],
                max_length=32,
                verbose_name="Действие",
            ),
        ),
    ]
